# Generated by Django 4.1.7 on 2023-03-04 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Course',
            new_name='Branch',
        ),
        migrations.RenameModel(
            old_name='Department',
            new_name='District',
        ),
        migrations.RenameModel(
            old_name='Order',
            new_name='Person',
        ),
    ]
