# Generated by Django 4.1.7 on 2023-03-05 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0003_rename_course_branch_branch_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='course',
            new_name='account',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='department',
            new_name='branch',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='purpose',
            new_name='district',
        ),
    ]
